apiVersion: v1
kind: Service
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: client
      image: mikhailadriaanse/multi-client
      ports:
        - containerPort: 3000